// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu3QC9Er0RnrWCiqC7A9QXeZTuwB4GF8k',
    appId: '1:786741050162:web:6645144639b1538115b52b',
    messagingSenderId: '786741050162',
    projectId: 'project-green-d32ed',
    authDomain: 'project-green-d32ed.firebaseapp.com',
    storageBucket: 'project-green-d32ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRzpAe8sI-xtiX3OtpH5kMxNAh0WLhKzs',
    appId: '1:786741050162:android:86501064833d7a4015b52b',
    messagingSenderId: '786741050162',
    projectId: 'project-green-d32ed',
    storageBucket: 'project-green-d32ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe6rYIfzxbUdJZdhaGDtgKv7EGp1XlwA8',
    appId: '1:786741050162:ios:17971ff9c0698b5e15b52b',
    messagingSenderId: '786741050162',
    projectId: 'project-green-d32ed',
    storageBucket: 'project-green-d32ed.firebasestorage.app',
    iosBundleId: 'com.example.projHiraya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu3QC9Er0RnrWCiqC7A9QXeZTuwB4GF8k',
    appId: '1:786741050162:web:3135cab9082c034915b52b',
    messagingSenderId: '786741050162',
    projectId: 'project-green-d32ed',
    authDomain: 'project-green-d32ed.firebaseapp.com',
    storageBucket: 'project-green-d32ed.firebasestorage.app',
  );
}
